### PR TITLE
readability improvement and a bug fix

### PR DESCRIPTION
**Pull request by waspinator**
Added prefixes to constants and global variables
 fixed adjusted current percentage calculation some more
 renamed DAC variables and cleaned up equation

### CODE REVIEW

**Comment by wigman27** [comment]
G'Day Patrick,

No problem at all, I am very glad people are getting something out of it.

Yes, I think you have miss understood my adjustedCurrent equations. First of all let's have a look at what setDac(dacCurrent,dacCurrentSet) actually does, it sends a percentage of the voltage reference 2.048V out, so yes we could call it dacVoltage because that's actually what it is, however, that voltage output will directly result in a current being drawn so to make the code a little easier I left it as dacCurrent. Let's take an 8 amp setting, this will require a DAC output voltage of 2.000V (4000 binary number) as this voltage will drop through the voltage divider formed at R18 and R17 to 0.8V, resulting in the op-amp and MOSFET allowing 8A to flow.

Because the LM324 doesn't have the best offset voltage, the 2.000v isn't actually 2.000V when it gets there, plus the tolerances in R18 and R17 will effect it also. This is why I introduced the adjust current function to eliminate these errors. The Op-amp is taking care of all of the rapid changing and the oscillation is taken care of with compensating resistors R15 and R16 and capacitor C3. This in itself is a PID controller with feedback (I hated that subject :-) )

So now let's have a look at the original function.
```
adjustedCurrent = (setCurrent / measuredCurrent) * setCurrent; // Turn the current error between set and measured into a percentage so it can be adjusted
```
Lets say we have a set current of 1A from the encoder and a measured current of 1.010A, the adjusted current will end up being (1/1.010) * 1 = 0.99A which will then be converted into a voltage to be sent to the op-amp. So it will drop the adjusted set current so the measured current is as close as possible to the actual set current.

Now let's have a look at your function with the same values 

```
g_adjustedCurrent = (abs(g_setCurrent - g_measuredCurrent) / g_setCurrent) * 100.0; // Turn the current error between set and measured into a percentage so it can be adjusted
```

((1-1.010)/1) * 100 = -1 So it would then try and set it to a negative. See what I mean, it's a percentage error of the setCurrent, not an actual percentage.

So let's have a look in this table to see what the software is doing,

Time | setCurrent (by encoder) | measuredCurrent | adjustedCurrent (sent to DAC) | error
------------ | ------------- | ------------- | ------------- | -------------
0 | 1.000 | N/A | 1.000 | N/A
1 | 1.000 | 1.010 | 0.990 | 1%
2 | 1.000 | 1.000 | 0.990 | 0%
3 | 1.000 | 1.000 | 0.990 | 0%

This will come in at 2 and 3 to stop the DAC being set back to 1.000 instead of 0.990. 
```
if (roundedMeasuredCurrent != setCurrent)
```

If you can take out that change in formula I will test it out and merge the request.

I hope that makes a little more sense, it will not remove the offsets completely as the voltage is buffered through an op-amp but it certainly takes a lot of precision and off-set errors out of the equations. Thanks mate for your contributions :-).

Lee

**Comment by waspinator** [comment]
Hi Lee,

Thanks for the explanation. Makes things clearer now.

I tried using the original adjustCurrent equation but I was always getting less current than what I set. I changed the equation to what I think is a P controller and it brought down my errors to almost 0.

I'd be interested to know if it helps with your hardware at all. (I'm using different components)

Patrick

**Comment by wigman27** [comment]
Hi Patrick,

I'm really sorry but your new adjust calculations oscillated badly from the set current by around 5 and 10 mA plus the usual 3mA measurement error, where as the original formula sometimes oscillated between 0.5mA plus the usual 3mA offset (im going to upgrade the LM324 in the next revision). The 0.5mA oscillation is expected as it is 1 least significant bit of the 12 bit DAC and ADC with 2.048V voltage reference.

I love the rest of your additions including the rounding function. So please revert back to the original current adjust formula, update the version number and descriptions and I would love to merge!

Thanks again mate! I really appreciate your work.

Lee

**Comment by waspinator** [comment]
Hmm, I think a PI controller might work better than, but since your offset is acceptable I guess it's okay not to bother with it at all. I had a 10mA offset that went away with just the P controller, but I didn't check how bad the oscillations were.

Which op amp are you looking into? I'm using the MCP6004 right now, but it could probably be replaced too.

**Comment by wigman27** [comment]
Thanks very much for this!

I have now closed it, can you email me at lee@wigginsclan.net to continue this conversation about op-amps and future plans?

**Pull request merged**
